services:
  devcontainer_app:
    image: 'mcr.microsoft.com/devcontainers/java:1-21'
    volumes:
      - ../:/workspace/:cached
    command: 'sleep infinity'
    network_mode: 'service:postgres_db'

  postgres_db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
