services:
  devcontainer_app:
    image: 'mcr.microsoft.com/devcontainers/java:1-17'
    volumes:
# mount project's parent folder as /workspace,
# so the project itself will be available at /workspace/<project-name>
      - ../../:/workspace/:cached
    command: 'sleep infinity'
# network with service_db
    network_mode: 'service:postgres_db'

  postgres_db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
